# Generated by Django 3.2.4 on 2022-11-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay_order', '0005_auto_20221123_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tax',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
